version: "3.8"

services:
  jenkins:
    build:
        context: ./
    restart: unless-stopped
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock //// find the host path and implement here
      - ${HOST_JENKINS_DATA}:/var/jenkins_home
    ports:
      - "${HOST_WWW}:8080"
      - "${HOST_OTHER}:50000"
    image: whanos-jenkins
    environment:
      - ADMIN_PASSWORD= "admin"
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=tcp://dind-service:2375
    depends_on:
      - docker
  docker:
    image: docker:dind
    restart: unless-stopped
    privileged: true
    environment:
     - DOCKER_TLS_CERTDIR=
