FROM node:14.17.5

RUN apt-get install apk
RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app
ONBUILD WORKDIR /app
ONBUILD RUN npm install --production=false
ONBUILD CMD ["node", "."]